@abstract
class_name SettingsTRKeys
extends RefCounted


const SETTINGS_TITLE: StringName = "UI.SETTINGS.TITLE"

const VOLUME_MASTER: StringName = "UI.SETTINGS.VOLUME.MASTER"
const VOLUME_MUSIC: StringName = "UI.SETTINGS.VOLUME.MUSIC"
const VOLUME_SFX: StringName = "UI.SETTINGS.VOLUME.SFX"

const CAMERA_SENSITIVITY: StringName = "UI.SETTINGS.CAMERA.MOUSE.SENSITIVITY"
const CAMERA_MOUSE_SENSITIVITY: StringName = "UI.SETTINGS.CAMERA.SENSITIVITY"

const SCREEN_RESOLUTION: StringName = "UI.SETTINGS.SCREEN.RESOLUTION"
const WINDOW_MODE: StringName = "UI.SETTINGS.WINDOW.MODE"
const GRAPHIC_QUALITY: StringName = "UI.SETTINGS.GRAPHIC.QUALITY"

const LANGUAGE: StringName = "UI.SETTINGS.LANGUAGE"

const CUSTOMIZE_CONTROLS: StringName = "UI.SETTINGS.CUSTOMIZE.CONTROLS"
const BUTTON_CUSTOMIZE: StringName = "UI.SETTINGS.BUTTON.CUSTOMIZE"


func _dummy_extraact_keys() -> void:
	tr(SETTINGS_TITLE)

	tr(VOLUME_MASTER)
	tr(VOLUME_MUSIC)
	tr(VOLUME_SFX)

	tr(CAMERA_SENSITIVITY)
	tr(CAMERA_MOUSE_SENSITIVITY)

	tr(SCREEN_RESOLUTION)
	tr(WINDOW_MODE)
	tr(GRAPHIC_QUALITY)

	tr(LANGUAGE)

	tr(CUSTOMIZE_CONTROLS)
	tr(BUTTON_CUSTOMIZE)
